trigger:
  branches:
    include:
      - master
      - production
    exclude: ["master", "feature*", "README.md","helm"] #

pool:
 vmImage: Ubuntu
  # name: pool
  # demands:
  #   - Java -equals 17.0.17
  #   - Maven -equals 3.8.7
  #   - Terraform -equals Yes
  #   - Trivy -equals Yes
  #   - Node.js -equals 18.20.8
  #   - Snyk -equals Yes
  #   - Agent.Name -equals raju


variables:
  - group: globel-variables
  - name: version  
    value: "1.0.0"
  - name: email 
    value: "dnsrinu143@gmail.com"
  - name: isDev
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: vd
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/production')]
  - name: dockerRegistryServiceConnection
    value: '25e8c454-3a15-4844-8f5b-c9998fd32ba9' 
  - name: imageRepository
    value: 'application-mysql' #Spring docker image name
  - name: containerRegistory   #AZURE ACR IMAGE NAME
    value: 'spring.azurecr.io'
  - name: dockerfikePath
    value: '${Build.SourceDirectory}/Dockerfile' 
  - name: tag
    value: v1.0.3 #$(Build.BuildId) 


stages:
  - stage: DEV
    pool:
      name: pool # TODO CAN RUN EACH STAGE DIFFERENT AGENT POOL NAME 
    condition: and(succeeded(), eq(variables['isDev'], true))
    variables:  
      stage_version: "1.0.6"
      stage_email: "dnsrinu143@gmail.com"      
    jobs:
      - job: mavan_package
        displayName: 'Create a jar File'
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Azure subscription 1(25e8c454-3a15-4844-8f5b-c9998fd32ba9)'
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
      - job: Trivy_scanning
        dependsOn: mavan_package
        displayName: 'trivy Scanning '
        condition: always() 
        variables:
          stage_version: "1.0.6"
          stage_email: "dnsrinu143@gmail.com"                    
        steps:         
          - script: pwd && ls -al
            displayName: "List Folder & Files"   
          - script: echo $(Build.BuildId)
            displayName: "Display The Build-ID"       
          - script: trivy fs .
            displayName: 'Scan current directory' 
          - script: trivy repo --branch master https://github.com/Srinu-rj/spring-food-app
            displayName: 'scanning github Repository'   
      - job: ArtifactName
        dependsOn: Trivy_scanning
        condition: always()
        displayName: 'ArtifactName '
        steps: 
          - task: Maven@3
            displayName: "Build Spring Boot JAR"
            inputs:
             mavenPomFile: "pom.xml"
             goals: "clean package -DskipTests"
             publishJUnitResults: false          
          - task: PublishPipelineArtifact@1
            displayName: "Publish Artifact"
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/target"
              artifact: "application-mysql"
          - task: DownloadPipelineArtifact@2
            displayName: "Download Artifact"
            inputs:
             artifact: application-mysql-DEV
             path: "$(Pipeline.Workspace)/app"
      - job: sonar_scan_server
        displayName: 'sonarqube scanning'      
        steps:
          - task: SonarQubePrepare@8
            inputs:
              SonarQube: 'sonarserver'
              scannerMode: 'other'
              extraProperties: |
                sonar.projectVersion=1.0.0.0
                      sonar.projectName=springsonarqube
                      sonar.sources=src/main/java/
                      sonar.language=java
                      sonar.sourceEncoding=UTF-8
          # - task: Maven@3
          #   inputs:
          #     mavenPomFile: '$(Build.SourcesDirectory)/sonarqube/sonarqubespring/pom.xml'
          #     goals: 'clean package'
          #     publishJUnitResults: true
          #     javaHomeOption: 'JDKVersion'
          #     mavenVersionOption: 'Default'
          #     mavenAuthenticateFeed: false
          #     effectivePomSkip: false
          #     sonarQubeRunAnalysis: true
          #     enabled: true                      
              
      - job: docker_build_and_push
        dependsOn: sonar_scan_server
        condition: always()
        displayName: 'docker login'
        steps:
          - task: Docker@2
            inputs:
             containerRegistry: 'dockerhub'
             command: 'login'
  
  # TEST
  - stage: QA
    pool:
      name: pool # TODO CAN RUN EACH STAGE DIFFERENT AGENT POOL NAME 
    condition: and(succeeded(), eq(variables['isDev'], true))
    variables:  
      stage_version: "1.0.6"
      stage_email: "dnsrinu143@gmail.com"      
    jobs:
      - job: mavan_package
        displayName: 'Create a jar File'
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Azure subscription 1(25e8c454-3a15-4844-8f5b-c9998fd32ba9)'
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
      - job: Trivy_scanning
        dependsOn: mavan_package
        displayName: 'trivy Scanning '
        condition: always() 
        variables:
          stage_version: "1.0.6"
          stage_email: "dnsrinu143@gmail.com"                    
        steps:         
          - script: pwd && ls -al
            displayName: "List Folder & Files"   
          - script: echo $(Build.BuildId)
            displayName: "Display The Build-ID"       
          - script: trivy fs .
            displayName: 'Scan current directory' 
          - script: trivy repo --branch master https://github.com/Srinu-rj/spring-food-app
            displayName: 'scanning github Repository'   
      - job: ArtifactName
        dependsOn: Trivy_scanning
        condition: always()
        displayName: 'ArtifactName '
        steps: 
          - task: Maven@3
            displayName: "Build Spring Boot JAR"
            inputs:
             mavenPomFile: "pom.xml"
             goals: "clean package -DskipTests"
             publishJUnitResults: false          
          - task: PublishPipelineArtifact@1
            displayName: "Publish Artifact"
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/target"
              artifact: "application-mysql"
          - task: DownloadPipelineArtifact@2
            displayName: "Download Artifact"
            inputs:
             artifact: application-mysql-QA
             path: "$(Pipeline.Workspace)/app"
             
      - job: sonar_scan_server
        displayName: 'sonarqube scanning'      
        steps:
          - task: SonarQubePrepare@8
            inputs:
              SonarQube: 'sonarserver'
              scannerMode: 'other'
              extraProperties: |
                sonar.projectVersion=1.0.0.0
                      sonar.projectName=springsonarqube
                      sonar.sources=src/main/java/
                      sonar.language=java
                      sonar.sourceEncoding=UTF-8
      - job: docker_build_and_push
        dependsOn: ArtifactName
        condition: always()
        displayName: 'docker login'
        steps:
          - task: Docker@2
            inputs:
             containerRegistry: 'dockerhub'
             command: 'login'  

  # PROD 
  - stage: PROD
    pool:
      name: pool # TODO CAN RUN EACH STAGE DIFFERENT AGENT POOL NAME 
    condition: and(succeeded(), eq(variables['isDev'], true))
    variables:  
      stage_version: "1.0.6"
      stage_email: "dnsrinu143@gmail.com"     
    jobs:
      - job: prod_maven_package
        displayName: 'PROD MAVEN PACKAGE'
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Azure subscription 1(25e8c454-3a15-4844-8f5b-c9998fd32ba9)'
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false



