trigger:
  branches:
    include:
      - master
      - production
    exclude: ["master", "feature*", "README.md"]

pool:
  name: pool
  # demands:
  #   - Java -equals 17.0.17
  #   - Maven -equals 3.8.7
  #   - Terraform -equals Yes
  #   - Trivy -equals Yes
  #   - Node.js -equals 18.20.8
  #   - Snyk -equals Yes
  #   - Agent.Name -equals raju


variables:
  - group: globel-variables
  - name: version  
    value: "1.0.0"
  - name: email 
    value: "dnsrinu143@gmail.com"
  - name: isDev
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: vd
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/production')]
  - name: dockerRegistryServiceConnection
    value: '25e8c454-3a15-4844-8f5b-c9998fd32ba9' 
  - name: imageRepository
    value: 'application-mysql' #Spring docker image name
  - name: containerRegistory   #AZURE ACR IMAGE NAME
    value: 'spring.azurecr.io'
  - name: dockerfikePath
    value: '${Build.SourceDirectory}/Dockerfile' 
  - name: tag
    value: v1.0.3 #$(Build.BuildId) 


stages:
  - stage: maven_clean
    condition: and(succeeded(), eq(variables['isDev'], true))
    variables:  #todo optinal
      stage_version: "1.0.6"
      stage_email: "dnsrinu143@gmail.com"        
    jobs:
     - job: maven_clean
       steps:
         - task: Maven@4
           inputs:
             azureSubscription: 'Azure subscription 1(25e8c454-3a15-4844-8f5b-c9998fd32ba9)'
             mavenPomFile: 'pom.xml'
             publishJUnitResults: true
             testResultsFiles: '**/surefire-reports/TEST-*.xml'
             javaHomeOption: 'JDKVersion'
             mavenVersionOption: 'Default'
             mavenAuthenticateFeed: false
             effectivePomSkip: false
             sonarQubeRunAnalysis: false
         - script: echo $(Build.BuildId)
           displayName: "Display The Build-ID"
         - script: mvn clean install 
           displayName: "maven clean install"
         - script: mvn package
           displayName: "packaging the application"
         - script: pwd && ls -al
           displayName: "List Folder & Files"         
         - task: CopyFiles@2
           inputs:
             SourceFolder: '$(System.DefaultWorkingDirectory)'
             Contents: '**'
             TargetFolder: '$(System.DefaultWorkingDirectory)/target'
         - task: PublishBuildArtifacts@1
           inputs:
             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
             ArtifactName: 'drop'
             publishLocation: 'Container'

  - stage: security
    condition: and(succeeded(), eq(variables['isDev'], true))
    pool:
     name: pool 
    variables:  
      stage_version: "1.0.6"
      stage_email: "dnsrinu143@gmail.com"   
    jobs:
     - job: security_check
       steps:
        - script: echo $(Build.BuildId)
          displayName: "Display The Build-ID"       
        - script: trivy fs .
          displayName: 'Scan current directory' 
        - script: trivy repo --branch master https://github.com/Srinu-rj/spring-food-app
          displayName: 'scanning github Repository'

  - stage: DockerBuildAndTrivyScan
    condition: and(succeeded(), eq(variables['isDev'], true))
    pool:
     name: pool 
    variables:  
      stage_version: "1.0.6"
      stage_email: "dnsrinu143@gmail.com"   
    jobs:
     - job: docker_build_and_push
       steps:
        - task: Docker@2
          inputs:
             containerRegistry: 'dockerhub'
             command: 'login'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              az version
          displayName: 'Install Azure CLI'
          
        - task: AzureCLI@2
          displayName: 'acr login...'
          inputs:
            azureSubscription: 'Azure subscription 1(25e8c454-3a15-4844-8f5b-c9998fd32ba9)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 'az acr login --name=$(containerRegistory)'
        - task: Docker@2
          displayName: 'build image'
          inputs:
            containerRegistry: 'dockerhub'
            repository: '$(imageRepository)'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: 
              $(tag)

        



