# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  # vmImage: ubuntu-latest
  name: pool

stages:
  - stage: maven_clean
    jobs:
      - job: maven_clean_install
        displayName: 'maven clean'
        steps:
        - checkout: self
        - task: Maven@4
          inputs:
            azureSubscription: 'Azure subscription 1(25e8c454-3a15-4844-8f5b-c9998fd32ba9)'
            mavenPomFile: 'pom.xml'
            goals: 'clean'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

  - stage: maven_validate
    jobs:
      - job: maven_validate
        displayName: 'maven validate'
        steps:
        - checkout: self
        - task: Maven@4
          inputs:
            azureSubscription: 'Azure subscription 1(25e8c454-3a15-4844-8f5b-c9998fd32ba9)'
            mavenPomFile: 'pom.xml'
            goals: 'validate'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            
  - stage: maven_package
    jobs:
      - job: maven_package
        displayName: 'maven package'
        steps:
        - checkout: self
        - task: Maven@4
          inputs:
            azureSubscription: 'Azure subscription 1(25e8c454-3a15-4844-8f5b-c9998fd32ba9)'
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
