apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-blue
  namespace: app-namespace
spec:
  replicas: 7
  selector:
    matchLabels:
      app: app-deployment
      env: blue # todo blue-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
#      nodeName: local-cluster-m04 # you can specify with in Particular node.
#      nodeSelector:
#        kubernetes.io/hostname: "new-cluster"
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: key
#                    operator: In
#                    values:
#                      - value
      containers:
        - name: app-deployment
          image: srinu641/spring-image:latest
          imagePullPolicy: IfNotPresent #the image is pulled only if it is not already present locally.
          resources:
            requests:
              memory: 20Mi
              cpu: "0.25"
            limits:
              memory: 400Mi
              cpu: "1"
          env:   # Setting Environmental Variables
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: aws-rds-server
                  key: secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: password
          ports:
            - containerPort: 8998
              name: app-deployment
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistance-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---

#            - name: DB_HOST   # Setting Database host address
#              value: mysql
#            - name: DB_NAME  # Setting Database name
#              value: jdbc:mysql://rds-database.cn2aysi4umep.us-east-1.rds.amazonaws.com/spring
#            - name: DB_USERNAME  # Setting Database username
#              value: root
#            - name: DB_PASSWORD # Setting Database password
#              value: srinu1234

---
#todo  Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-namespace
spec:
  ports:
    - protocol: "TCP"
      port: 8998    # TODO Port inside the cluster
      targetPort: 8998   #TODO  Port exposed to the outside
  selector:
    app: app-deployment
    env: blue
  type: NodePort #todo ClusterIP
---

