apiVersion: v1
kind: PersistentVolumeClaim #todo PersistentVolume
metadata:
  name: mysql-pv-claim  # todo name of PVC essential for identifying the storage data
  namespace: database-production
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteMany #todo This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 5Gi # todo This will tell kubernetes about the amount of space we are trying to claim.
#  storageClassName: "demo-storage"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database-production
  labels:
    app: mysql
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.41
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin1234aA  # Replace with a secret in production
            - name: MYSQL_DATABASE
              value: spring  # Database name only
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: database-production
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None
---