apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-aws-ebs-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: <volume-id> #difine EBS VOLUME HERE
    fsType: ext4