apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-pods-roles
  namespace: app-namespace
rules:
  - apiGroup: [""]
    resources: ["pods","pods/exec"]
    verbs: ["get","delete","watch","list","create"]

  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list", "delete", "create" ]

  - apiGroups: [""]  #todo for app-service
    resources: ["service"]
    verbs: ["get","delete","watch","list","create"]

  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list", "delete", "create" ]

  - apiGroups: [ "" ] #todo for mysql-service
    resources: [ "service" ]
    verbs: [ "get","delete","watch","list","create" ]

