## Todo for all Database
#spring.datasource.url=jdbc:mysql://172.18.183.16:3306/spring
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
#
##todo address Database
#spring.restaurant.datasource.url=jdbc:mysql://172.18.183.16:3306/restaurantDatabase
#spring.restaurant.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.restaurant.datasource.username=root
#spring.restaurant.datasource.password=root
#
##todo restaurant Database -> 172.18.183.16
#spring.address.datasource.url=jdbc:mysql://172.18.183.16:3306/address
#spring.address.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.address.datasource.username=root
#spring.address.datasource.password=root
#
#spring.bill.datasource.url=jdbc:mysql://172.18.183.16:3306/bill
#spring.bill.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.bill.datasource.username=root
#spring.bill.datasource.password=root
#
#spring.category.datasource.url=jdbc:mysql://172.18.183.16:3306/category
#spring.category.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.category.datasource.username=root
#spring.category.datasource.password=root
#
#spring.customer.datasource.url=jdbc:mysql://172.18.183.16:3306/customer
#spring.customer.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.customer.datasource.username=root
#spring.customer.datasource.password=
#
#spring.foodCart.datasource.url=jdbc:mysql://172.18.183.16:3306/foodCart
#spring.foodCart.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.foodCart.datasource.username=root
#spring.foodCart.datasource.password=root
#
#spring.item.datasource.url=jdbc:mysql://172.18.183.16:3306/item
#spring.item.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.item.datasource.username=root
#spring.item.datasource.password=root
#
#spring.orderItem.datasource.url=jdbc:mysql://172.18.183.16:3306/orderItem
#spring.orderItem.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.orderItem.datasource.username=root
#spring.orderItem.datasource.password=root
#
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect