apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: database
  labels:
    app: postgres
    tier: database
spec:
#  storageClassName: standard # Ensure this matches your cluster's StorageClass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---