#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: mysql-backup-job
#spec:
#  backoffLimit: 5 # todo to Create BackUp Pods
#  activeDeadlineSeconds: 100 # Stop the job after 100 seconds if incomplete
#  ttlSecondsAfterFinished: 60 # Delete the job 60 seconds after completion
#  template:
#    spec:
#      containers:
#        - name: mysql
#          image: mysql:8.0
#          command: [ "/bin/sh", "-c" ]
#          args:
#            [
#              'mysqldump -h mysql-service.default.svc.cluster.local -u root -p${MYSQL_PASSWORD} --all-databases > /usr/share/mysqlbackup/backup-$(date +"%d%m%Y-%H%M%S").sql',
#            ]
#          volumeMounts:
#            - mountPath: "/usr/share/mysqlbackup/"
#              name: mysqlbackup
#          env:
#            - name: MYSQL_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  key: root-password # I HAVE TO CHANGE
#                  name: mysql-secret
#      volumes:
#        - name: mysqlbackup
#          persistentVolumeClaim:
#            claimName: mysqlbackup
#      restartPolicy: Never
#---
##TODO FRO MONGODB
##apiVersion: batch/v1
##kind: Job
##metadata:
##  name: mongodb-backup-job
##spec:
##  backoffLimit: 5
##  activeDeadlineSeconds: 100 #
##  ttlSecondsAfterFinished: 60 # delete job after 60 seconds
##  template:
##    spec:
##      containers:
##        - name: mongodb
##          image: mongo
##          command: [ "/bin/sh", "-c" ]
##          args:
##            [
##              'mongodump --uri "mongodb://test1:${MONGO_PASSWORD}@mongo-0.mongo.default.svc.cluster.local:27017,mongo-1.mongo.default.svc.cluster.local:27017,mongo-2.mongo.default.svc.cluster.local:27017/?replicaSet=rs0&readPreference=secondaryPreferred&authSource=admin&ssl=false" -o /usr/share/mongodump/$(date +"%d%m%Y-%H%M%S")',
##            ]
##          volumeMounts:
##            - mountPath: "/usr/share/mongodump/"
##              name: mongodump
##          env:
##            - name: MONGO_PASSWORD
##              valueFrom:
##                secretKeyRef:
##                  key: password
##                  name: mongodb-secret
##      volumes:
##        - name: mongodump
##          persistentVolumeClaim:
##            claimName: mongodump
##      restartPolicy: Never
#---
