---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-url
  namespace: app-namespace
stringData:
  DATABASE_URL: jdbc:mysql://rds-database.cn2aysi4umep.us-east-1.rds.amazonaws.com/spring
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: root # required field for kubernetes.io/basic-auth
  password: srinu1234 # required field for kubernetes.io/basic-auth
---
#apiVersion: v1
#kind: Secret
#metadata:
#  # Note how the Secret is named
#  name: bootstrap-token-5emitj
#  # A bootstrap token Secret usually resides in the kube-system namespace
#  namespace: kube-system
#type: bootstrap.kubernetes.io/token
#stringData:
#  auth-extra-groups: "system:bootstrappers:kubeadm:default-node-token"
#  expiration: "2020-09-13T04:39:10Z"
#  # This token ID is used in the name
#  token-id: "5emitj"
#  token-secret: "kq4gihvszzgn1p0r"
#  # This token can be used for authentication
#  usage-bootstrap-authentication: "true"
#  # and it can be used for signing
#  usage-bootstrap-signing: "true"
---