---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-url
  namespace: app-namespace
stringData:
  DATABASE_URL: jdbc:mysql://rds-database.cn2aysi4umep.us-east-1.rds.amazonaws.com/spring
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: secret-basic-auth
#  namespace: default
#type: kubernetes.io/basic-auth
#stringData:
#  username: root # required field for kubernetes.io/basic-auth
#  password: srinu1234 # required field for kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: app-namespace
type: Opaque
data:
  username: cm9vdAo=
  password: c3JpbnUxMjM0Cg==
---