---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-rds-url
  namespace: database-production
stringData:
  DATABASE_URL: jdbc:mysql://database-1.c74g48i8uz77.us-west-2.rds.amazonaws.com:3306/spring

#  DATABASE_URL: amRiYzpteXNxbDovL2RhdGFiYXNlLmNuMmF5c2k0dW1lcC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20vc3ByaW5n

#  DATABASE_URL: amRiYzpteXNxbDovL3Jkcy1kYXRhYmFzZS5jbjJheXNpNHVtZXAudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tL3NwcmluZw==
---
apiVersion : v1
kind : Secret
metadata:
  name : mysql-secrets
  namespace: database-production
data:
  username : YWRtaW4=
  password : c3JpbnUxMjM0
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: database-production
type: Opaque
data:
  root-password: c3JpbnUxMjM0
  user: YWRtaW4=
  password: c3JpbnUxMjM0
---
apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
  namespace: database-production
data:
  host : mysql
  dbName: spring
---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: rds-configmap
#  namespace: database-production
#data:
#  db-url: jdbc:mysql://database-1.c74g48i8uz77.us-west-2.rds.amazonaws.com/spring
---