name: spring boot CICD Deploying to AWS ECR AND EKS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    JAVA_VERSION: '21'  # TODO Set the Java Version to 21
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    IMAGE_NAME: spring-boot-app



jobs:
  Building-and-Testing: #Job Name
    runs-on: ubuntu-latest #TODO The type of machine to run the job on Ubuntu | Windows | MacOS
    permissions:
      contents: read
      packages: write
    steps:
      # TODO
      - name: just a test step
        run: echo "This workflow runs at Every One Hour "
      # TODO  Code checkout step
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}   # Todo Make It '21'
          distribution: 'temurin' # 'adopt'
          architecture: x64
          cache: 'maven' # Strongly recommended for faster builds!
          cache-dependency-path: 'pom.xml' # Or '**/pom.xml' for multi-module projects

      - name: mvn clean package
        run: mvn clean package
      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: <dockerhub-username>/custom-nginx
          args: --file=Dockerfile --severity-threshold=high
          json: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
      - name: Convert Snyk JSON to SARIF
        uses: garethr/snyk-to-sarif@master
        with:
          input: snyk.json
          output: snyk.sarif
      - name: Upload scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
